import type { DynamicDate } from './dynamicDates'

// Registry of every dynamic date wired into a page. These are the DEFAULTS (current
// page values) so the admin dashboard shows each page fully pre-populated — you can
// change one field and Save. Saving stores an override in the DB; until then the page
// renders these values. `label` names the page so you know where each date lives.
const off = { enabled: false, title: '', link: '', color: '#E8A849' }

export const DYNAMIC_DATE_REGISTRY: DynamicDate[] = [
  {
    slug: 'masterclass',
    label: 'Masterclass — Rewrite in Real Time (/masterclass)',
    pageUrl: '/masterclass',
    title: 'Rewrite in Real Time',
    description: 'Live Masterclass',
    date: 'June 13, 2026',
    heroImage: '/images/go9/speaking-event.jpg',
    cta: { ...off },
  },
  {
    slug: 'pr-retreat',
    label: 'Puerto Rico Retreat (/pr-retreat)',
    pageUrl: '/pr-retreat',
    title: 'Puerto Rico Retreat',
    description: 'A Caribbean reset for women ready to revive, reconnect, and rise.',
    date: 'March 28–April 3, 2027',
    heroImage: '/images/retreat/retreat-group-03.jpg',
    cta: { ...off },
  },
  {
    slug: 'workshops',
    label: 'Workshops (/workshops)',
    pageUrl: '/workshops',
    title: 'Workshops & Corporate Training',
    description: 'Live workshops for teams and leaders.',
    date: 'See schedule',
    heroImage: '/images/go9/corporate.jpg',
    cta: { ...off },
  },
  {
    slug: 'vision-board',
    label: 'Vision Board Party (/vision-board)',
    pageUrl: '/vision-board',
    title: 'Vision Board Party',
    description: 'Quarterly. Leave the date blank to auto-advance; type a date here to override what shows on the page.',
    date: '',
    time: '5–7 PM EST',
    heroImage: '/images/krystalore/REM08628.jpg',
    cta: { ...off },
  },
  {
    slug: 'bombshell-bootcamp',
    label: 'Bombshell Bootcamp (/bombshell-bootcamp)',
    pageUrl: '/bombshell-bootcamp',
    title: 'Bombshell Bootcamp',
    description: 'Activate your Freedom Formula.',
    date: 'Enrolling now',
    heroImage: '/images/go9/fitness.jpg',
    cta: { ...off },
  },
  {
    slug: 'upcoming-events',
    label: 'Upcoming Events (/upcoming-events)',
    pageUrl: '/upcoming-events',
    title: 'Upcoming Events',
    description: 'Live events & speaking engagements.',
    date: 'See schedule',
    heroImage: '/images/go9/keynote.jpg',
    cta: { ...off },
  },
  {
    slug: 'products',
    label: 'Products (/products)',
    pageUrl: '/products',
    title: 'Products',
    description: 'Krystalore products & lifestyle offerings.',
    date: '',
    heroImage: '/images/go9/group-evening.webp',
    cta: { ...off },
  },
  {
    slug: 'health-mastery',
    label: 'Health Mastery (/health-mastery)',
    pageUrl: '/health-mastery',
    title: 'Health Mastery',
    description: 'Group coaching for entrepreneurs and leaders.',
    date: 'Enrolling now',
    heroImage: '/images/health-mastery/hero.webp',
    cta: { ...off },
  },
  {
    slug: 'million-dollar-body',
    label: 'Million Dollar Body (/million-dollar-body)',
    pageUrl: '/million-dollar-body',
    title: 'Million Dollar Body',
    description: 'The signature body-transformation program.',
    date: 'Enrolling now',
    heroImage: '/images/go9/fitness.jpg',
    cta: { ...off },
  },
  {
    slug: 'shyft-mastery',
    label: 'ShYft Mastery (/shyft-mastery)',
    pageUrl: '/shyft-mastery',
    title: 'ShYft Mastery',
    description: 'Rebuild your body, mind, and momentum.',
    date: 'Enrolling now',
    heroImage: '/images/go9/fitness-outdoor.jpg',
    cta: { ...off },
  },
  {
    slug: 'business-vital',
    label: 'Business Vital (/business-vital)',
    pageUrl: '/business-vital',
    title: 'Business Vital',
    description: 'Make your business healthy, profitable, and built to last.',
    date: 'Enrolling now',
    heroImage: '/images/go9/corporate.jpg',
    cta: { ...off },
  },
  {
    slug: 'relationship-remodel',
    label: 'Relationship Remodel (/relationship-remodel)',
    pageUrl: '/relationship-remodel',
    title: 'Relationship Remodel',
    description: 'Rebuild and strengthen the relationships that matter.',
    date: 'Enrolling now',
    heroImage: '/images/go9/group-sunset-dresses.webp',
    cta: { ...off },
  },
  {
    slug: 'retreat',
    label: 'Retreats Hub (/retreat)',
    pageUrl: '/retreat',
    title: 'Krystalore Retreats',
    description: 'Transformational getaways for women ready to reset and rise.',
    date: 'Dates TBA',
    heroImage: '/images/retreat-destinations/cr-01.jpg',
    cta: { ...off },
  },
  {
    slug: 'cr-retreat',
    label: 'Costa Rica Retreat (/cr-retreat)',
    pageUrl: '/cr-retreat',
    title: 'Costa Rica Retreat',
    description: 'A tropical reset where you’re treated like a queen.',
    date: 'October 18–25, 2026',
    heroImage: '/images/retreat-destinations/cr-01.jpg',
    cta: { ...off },
  },
  {
    slug: 'tn-retreat',
    label: 'Tennessee Retreat (/tn-retreat)',
    pageUrl: '/tn-retreat',
    title: 'Tennessee Retreat',
    description: 'A lakeside escape to rest, reconnect, and be renewed.',
    date: 'Fall 2027 — dates TBD',
    heroImage: '/images/retreat-destinations/tn-airbnb/tn-lake-01.png',
    cta: { ...off },
  },
  {
    slug: 'rise-and-thrive',
    label: 'Rise & Thrive (/rise-and-thrive)',
    pageUrl: '/rise-and-thrive',
    title: 'Rise & Thrive',
    description: 'So much bigger than a fitness program — your next chapter.',
    date: 'July 27',
    heroImage: '/images/go6/tropical-porch-dress.jpg',
    cta: { ...off },
  },
  {
    slug: 'veteran-retreats',
    label: 'Veteran Retreats (/veteran-retreats)',
    pageUrl: '/veteran-retreats',
    title: 'Veteran Retreats',
    description: 'Restorative retreats honoring the women who served.',
    date: 'Dates TBA',
    heroImage: '/images/go9/veteran.jpg',
    cta: { ...off },
  },
  {
    slug: 'couples-retreats',
    label: 'Couples Retreats (/couples-retreats)',
    pageUrl: '/couples-retreats',
    title: 'Couples Retreats',
    description: 'Reconnect and strengthen your relationship, together.',
    date: 'Dates TBA',
    heroImage: '/images/retreat/retreat-01.jpg',
    cta: { ...off },
  },
]

export const REGISTRY_BY_SLUG = new Map(DYNAMIC_DATE_REGISTRY.map((r) => [r.slug, r]))
